<!-- <header class="banner text-white bg-cover" style="background: url('aset/img/banner-corporate-business-risk.jpg') top">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
      </div>
    </div>
  </div>
</header>
<div class="banner-content banner-bottom container-fluid mb-3r">
  <div class="text-left mb-20">
    <div class="border-bottom-blue"></div>
  </div>
  <div class="title text-white ">
    <?= $page_name; ?>
  </div>
  <div class="div-link link-white" data-aos="fade-right">
    <ul>
      <li><a href="<?= site_url(); ?>">Home</a></li>
      <li class="line-up-white"><span class="visible">i</span></li>
      <li><a href="<?= site_url("business-solutions"); ?>">Business Solutions</a></li>
      <li class="line-up-white"><span class="visible">i</span></li>
      <li><a href="<?= current_url(); ?>"><?= $page_name; ?></a></li>
    </ul>
  </div>
</div> -->
<section class="section  pt-zero text-left pb-zero">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="content p-3r mb-3r pt-zero pt-3r" >
         	<h3 align="center">ELIXIR TECHNOLOGY</h3>
			<h3 align="center">GENERAL TERMS AND CONDITIONS</h3>
			<h3 align="center">(BIZINSIGHTS SERVICES)</h3>
			<p><br>
				These General Terms and Conditions (hereinafter referred to as "General T&amp;Cs") shall govern the use of the services offered by Elixir Technology Pte Ltd or a member of the Elixir Technology Group of Companies (hereinafter collectively called "<span style="font-weight: bold;">Elixir Technology</span>").&nbsp; These General T&amp;Cs contain terms and conditions that are of general application to most of Elixir Technology's service offerings, and some of the terms below may not be applicable to you.&nbsp; The specific service requested by you may be subject to additional terms and conditions (hereinafter referred to as "Product-Specific Terms") that are either set out in the Application Form or on the website mentioned in the Application Form. The General T&amp;Cs and the Product Specific Terms together, shall be referred to as "Agreement".<br>
				</p>
			<p>Unless explicitly stated otherwise, any new feature or features that augment or enhance the current services, including the release of or migration to new services, shall be subject to this Agreement.</p><br>
			<span style="font-weight: bold;"><i><span style="text-decoration: underline;">&nbsp;By completing and submitting the relevant application form for use of the Service or by using or otherwise assessing&nbsp; the Service, the Subscriber represents that it has read this Agreement and agrees to be bound by it.&nbsp;</span></i></span><br>
			<br>

			<ol style="list-style: disc inside none; list-style-type: decimal;"><span style="font-weight: bold;">
					<li>TERMINOLOGY</li></span>
				<p>In this Agreement, the following words and expressions have the meanings assigned to them except where the context otherwise requires:</p>
				<p>(i)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Addressee"</span>&nbsp;of a Data Message or an Electronic Record means a person who is intended by the Originator to receive the Data Message or Electronic Record, but does not include an intermediary like Elixir Technology who sends, receives, stores or provides other service with respect to the Data Message or Electronic Record on behalf of the Originator or Address;</p><br>
				
				<p>(ii)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Data Message"</span>&nbsp;means information generated, sent, received or stored by electronic, optical or similar means, including but not limited to Application Programmatic Interface (API) call, electronic mail, facsimile, FTP service, or auto-synchronization;&nbsp;</p>
				<p>(iii)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Digital Signature"</span>&nbsp;means data in electronic form in, affixed to, or logically associated with, a Data Message or an Electronic Record, which may be used to identify the signatory in relation to the Data Message or Electronic Record and indicate the signatory's approval of the information contained therein; and a reference to "Digitally Sign" shall be construed accordingly;</p>
				<p>(iv)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Electronic Record"</span>&nbsp;means a record generated in digital form by an Information System, which can be:</p>&nbsp;&nbsp;&nbsp; (a)&nbsp;&nbsp;&nbsp; transmitted from an Information System or from one Information System to another; and<br>
				&nbsp;&nbsp;&nbsp; (b)&nbsp;&nbsp;&nbsp; stored in an Information System or other medium;<br>
				<br>
				
				<p>(v)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Elixir Technology"</span>&nbsp;is a reference to the Elixir Technology entity whose name appears on the Application Form, and in the absence of such name refers to Elixir Technology Pte Ltd;</p>
				<p>(vi)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Information System"</span>&nbsp;means a system for generating, sending, receiving, storing or otherwise processing Data Messages or Electronic Records;</p>
				<p>(vii)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Originator"</span>&nbsp; of a Data Message or an Electronic Record means a person by whom, or on whose behalf, the Data Message or Electronic Record purports to have been sent or generated prior to storage, if any, but does not include an intermediary like Elixir Technology who sends, receives, stores or provides other services with respect to the Data Message or Electronic Record on behalf of the Originator or Addressee;</p>
				<p>(viii)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Services"</span>&nbsp;means the service provided by Elixir Technology over the Internet to the Subscriber upon the Subscriber's application therefore;</p>
				<p>(ix)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Subscriber"</span>&nbsp;or&nbsp;<span style="font-weight: bold;">"you"</span>&nbsp;means the party identified on the Application form whose application is approved and accepted by Elixir Technology;</p>
				<p>(x)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Service Provider"</span>&nbsp;means the content or service provider to which on-line access is provided to the Subscriber via the Website or Services;</p>
				<p>(xi)&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-weight: bold;">"Website"</span>&nbsp;or&nbsp;<span style="font-weight: bold;">"Websites"</span>&nbsp;refers to the location of the webpages on the internet over which the Subscriber may assess for the purpose of using the Services and which are specifically described in the Application Form, and includes such other uniform resource locators as may be provided or substituted by Elixir Technology from time to time.</p><span style="font-weight: bold;">
					<li>REGISTRATION</li></span>
				<p>2.1&nbsp;&nbsp;&nbsp; In order to use the Services, you will need to become a Subscriber by:</p>
				<p>(i)&nbsp;&nbsp;&nbsp; submitting the relevant properly completed application form (<span style="font-weight: bold;">"Application Form"</span>), which may be requested from Elixir Technology's Service Provider or downloaded from its website;</p>
				<p>(ii)&nbsp;&nbsp;&nbsp; providing to Elixir Technology all ancillary information that Elixir Technology may require, including but not limited to information on every end user being granted access to and use of the&nbsp; Services; and</p>
				<p>(iii)&nbsp;&nbsp;&nbsp; paying all applicable fees, to Elixir Technology or its Service Provider.</p>
				<p>Upon completion of the above, Elixir Technology will issue to you passwords and user identification numbers to use the&nbsp;Services.&nbsp; Elixir Technology reserves the sole right not to accept any Application Form at its sole discretion.</p>
				<p>2.2&nbsp;&nbsp;&nbsp; This Agreement shall commence on the date of Elixir Technology's approval of your application for use of the&nbsp;Services and shall remain in force unless earlier terminated in accordance with the terms and conditions herein.</p><span style="font-weight: bold;">
					<li>AMENDMENTS TO TERMS AND CONDITIONS</li></span>
				<p>3.1&nbsp;&nbsp;&nbsp; Elixir Technology reserves the right to amend the terms and conditions of this Agreement from time to time.&nbsp; Amendments to the General T&amp;Cs will be effective after thirty (30) days have passed from the date of posting on the Website. Amendments to the Product Specific Terms will be effective after thirty (30) days have passed from the date of posting on the Website. IT IS THE SUBSCRIBER'S RESPONSIBILITY TO CHECK THE WEBSITE FROM TIME TO TIME FOR AMENDMENTS TO THIS AGREEMENT. BY USING OR CONTINUING TO USE THE SERVICES AT ANY TIME AFTER THIRTY (30) DAYS HAVE PASSED FROM THE DATE ANY AMENDMENTS ARE POSTED ON THE WEBSITE, YOU REPRESENT THAT YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS OF THIS AGREEMENT AS AMENDED.</p><span style="font-weight: bold;">
					<li>SCOPE OF SERVICES</li></span>
				<p>4.1&nbsp;&nbsp;&nbsp; Subject to the acceptance of the properly completed Application Form by Elixir Technology and payment of all applicable fees by the Subscriber, Elixir Technology will provide the Subscriber the&nbsp; Services, provided always that Elixir Technology reserves the right to modify, enhance, withdraw or suspend the&nbsp; Services, or any part thereof, at any time.&nbsp; Elixir Technology will advise the Subscriber of the changes thirty (30) days in advance where the changes will, in Elixir Technology's opinion, significantly alter the Services.</p>
				<p>4.2&nbsp;&nbsp;&nbsp; Elixir Technology may provide such training, technical support or professional, archival or other ancillary services (collectively "Other Services") to the Subscriber as Elixir Technology may decide or agree from time to time.&nbsp; Elixir Technology will inform the Subscriber of the nature of and conditions (including but not limited to any applicable charges) pertaining to such Other Services.&nbsp; Elixir Technology reserves the right to change the scope or conditions of such Other Services at its sole discretion and will notify the Subscriber of such revision, either in electronic or written form or by posting on the Website.</p>
				<p>4.3&nbsp;&nbsp;&nbsp; The Services will be made available during such hours as may be notified by Elixir Technology to the Subscriber.&nbsp; Elixir Technology reserves the right to alter or extend the service hours from time to time.</p>
				<p>4.4&nbsp;&nbsp;&nbsp; Access to and use of a Service Provider's services and facilities by the Subscriber may require the approval of the Service Provider.&nbsp; The Service Provider may impose its own terms and conditions and charges for access to and use of its services.&nbsp; The Subscriber is responsible for ensuring that it has obtained all necessary approvals, consents and permissions for access to and use of a Service Provider's services and facilities.</p><span style="font-weight: bold;">
					<li>SUBSCRIBER RESPONSIBILITIES</li></span>
				<p>5.1&nbsp;&nbsp;&nbsp; The Subscriber shall obtain, install and maintain such suitable equipment, software, and communication means as may be required to make connection to the World Wide Web and to use the Services, including the necessary computing and telecommunication facilities or other access devices, and other ancillary equipment.</p>
				<p>5.2&nbsp;&nbsp;&nbsp; The Subscriber is responsible for the confidentiality of the password(s) associated with the account and user identification number(s) assigned by Elixir Technology upon registration of the Subscriber for the Services.&nbsp; The Subscriber shall ensure control of the password(s) and user identification number(s) for authorised usage of the Services.&nbsp; Unless the contrary is proved, all communications and activities occurring under or referable to the Subscriber's user account, user identification number(s) or password shall be deemed to have been validly issued or authorised by the Subscriber.&nbsp; The Subscriber shall be liable for all costs, fees, and expenses arising from any communication and activity occurring under or referable to the Subscriber's user account, user identification number(s) or password.</p>
				<p>5.3&nbsp;&nbsp;&nbsp; The Subscriber agrees that access to and usage of the Services is for its own business purposes only.&nbsp; The Subscriber shall use the&nbsp;Services solely in the capacity of an end-user, and shall not, without Elixir Technology's prior written approval, reproduce, duplicate, copy, sell, resell, or exploit any portion of the Services, information obtained through the&nbsp;Services, or use or access to the Services.&nbsp; The Subscriber shall not use the Services for the provision of outsourcing or service bureau-like services, without Elixir Technology's express prior written permission.&nbsp; Elixir Technology may agree to the Subscriber's use of the Services to provide such services at a separate charge.</p>
				<p>5.4&nbsp;&nbsp;&nbsp; The Subscriber warrants and represents that the Subscriber or its nominees are duly authorised to upload, submit, transmit or otherwise deal with all content, information and data provided by the Subscriber, and that all such content, information and data provided is true, accurate, current and complete.</p>
				<p>5.5&nbsp;&nbsp;&nbsp; The Subscriber agrees not to submit, upload or transfer any unauthorised files, codes (including but not limited to viruses), documents and information, in the course of using the Services.</p>
				<p>5.6&nbsp;&nbsp;&nbsp; The Subscriber undertakes not to use the Services for or to carry out any activity that may be prohibited under the laws of Singapore or under any other applicable law.</p>
				<p>5.7&nbsp;&nbsp;&nbsp; The Subscriber hereby authorises Elixir Technology to deal with any data or information submitted by or to the Subscriber, in any manner, as Elixir Technology deems necessary to carry out the Services.</p>
				<p>5.8&nbsp;&nbsp;&nbsp; The Subscriber agrees to render all reasonable assistance to Elixir Technology, as Elixir Technology may request from time to time.</p>
				<p>5.9&nbsp;&nbsp;&nbsp; The Subscriber agrees to at all times indemnify and hold harmless Elixir Technology and its officers, employees and agents (<span style="font-weight: bold;">"those indemnified"</span>) from and against any loss (including reasonable legal costs and expenses) or liability reasonably incurred or suffered by any of those indemnified arising from:</p>&nbsp;&nbsp;&nbsp; (a)&nbsp;&nbsp;&nbsp; a breach by the Subscriber or its employees, agents or contractors of the terms of this Agreement; or<br>
				&nbsp;&nbsp;&nbsp; (b)&nbsp;&nbsp;&nbsp; any wilful, unlawful or negligent act or omission on the part of the Subscriber or its employees, agents or contractors.<br>
				<br>
				
				<p>5.10&nbsp;&nbsp;&nbsp; The Subscriber shall provide to Elixir Technology the Subscriber's contact details (e.g. address, telephone number, fax number, e-mail) and shall promptly update Elixir Technology from time to time on any change in such contact details.&nbsp; Where Elixir Technology is to send any notification to the Subscriber under this Agreement, Elixir Technology shall use reasonable efforts to do so at the Customer's contact details last provided to Elixir Technology.&nbsp; Elixir Technology shall not be liable if the Customer cannot be contacted through any one of the contact details after two (2) attempts made within a two (2) week period.</p><span style="font-weight: bold;">
					<li>DATA MESSAGES AND ELECTRONIC RECORDS</li></span>
				<p>6.1&nbsp;&nbsp;&nbsp; The Subscriber agrees that all Data Messages and Electronic Records to be sent through the Services will comply with all applicable legal requirements and such message requirements as Elixir Technology may prescribe from time to time.</p>
				<p>6.2&nbsp;&nbsp;&nbsp; Unless otherwise specified by Elixir Technology, the dispatch of a Data Message is for all purposes deemed to have occurred when the Data Message enters an Information System outside the control of the Originator or of any person who sent the data message on behalf of the Originator.</p>
				<p>6.3&nbsp;&nbsp;&nbsp; Unless otherwise specified by Elixir Technology, the receipt of a Data Message is for all purposes deemed to have occurred when the Data Message enters an Information System or an electronic mailbox or similar system of the Addressee.</p>
				<p>6.4&nbsp;&nbsp;&nbsp; Elixir Technology will not be responsible for any trouble or loss caused by disputes (i) between the Subscriber and a Service Provider or (ii) between a Subscriber and another Subscriber relating to the dispatch or receipt of Data Messages or Electronic Records.</p>
				<p>6.5&nbsp;&nbsp;&nbsp; The period between "dispatch" and "receipt", as specified in Clauses 6.2 and 6.3 above, is indispensable for Elixir Technology for the conversion of format and transference of Data Message or Electronic Record etc.&nbsp; Elixir Technology will not be responsible for any damage or loss caused by the occurrence of the said period.</p>
				<p>6.6&nbsp;&nbsp;&nbsp; Unless otherwise specified by Elixir Technology, a Data Message or an Electronic Record is deemed to be dispatched at the place where the Originator has his place of business, and is deemed to be received at the place where the Addressee has his place of business.&nbsp; For the purpose of this paragraph:-</p>
				<p>(i)&nbsp;&nbsp;&nbsp; If the Originator or the Addressee has more than one place of business, the place of business is that which has the closest relationship to the underlying transaction or, where there is no underlying transaction, the principal place of business; or</p>
				<p>(ii)&nbsp;&nbsp;&nbsp; If the Originator or the Addressee does not have a place of business, reference is to be made to the habitual residence of the Originator or the Addressee.</p>
				<p>6.7&nbsp;&nbsp;&nbsp; If the Subscriber receives any Data Messages or Electronic Records addressed to another Subscriber or a third party which was wrongfully forwarded to him, he shall:-</p>
				<p>(i)&nbsp;&nbsp;&nbsp; notify, and return the Data Messages or Electronic Records to, the Originator through Elixir Technology as soon as possible;</p>
				<p>(ii)&nbsp;&nbsp;&nbsp; destroy all copies of the Data Messages or Electronic Records afterwards and keep the contents of the Data Message confidential.</p><span style="font-weight: bold;">
					<li>WRITING AND SIGNATURE REQUIREMENTS</li></span>
				<p>7.1&nbsp;&nbsp;&nbsp; The Subscriber agrees that, to the maximum extent permissible by law:-</p>
				<p>(i)&nbsp;&nbsp;&nbsp; a Data Message or an Electronic Record made and presented in accordance with Elixir Technology's specified message requirements and procedures will in any event and for all purposes be treated and deemed the same as a document in writing with the same content.</p>
				<p>(ii)&nbsp;&nbsp;&nbsp; a Data Message or an Electronic Record with a Digital Signature made in accordance with Elixir Technology's message requirements and procedures will in any event and for all purposes be treated and deemed the same as a document in writing physically signed by the party who made the Digital Signature with the same content.</p>
				<p>(iii)&nbsp;&nbsp;&nbsp; a Data Message or an Electronic Record, whether Digitally Signed or not, sent to or communicated with the Addressee through Elixir Technology's&nbsp; Services will in any event and for all purposes be treated and deemed to have been physically delivered and communicated with the Addressee.</p>
				<p>7.2&nbsp;&nbsp;&nbsp; The Subscriber shall inform other relevant Subscribers through Elixir Technology if the Subscriber is aware of any prohibition or restriction by the laws of any relevant jurisdiction, or any inconsistency with such laws, relating to any of the provisions specified in this Agreement or any contents of a Data Message or Electronic Record sent or received by it.</p>
				<p>7.3&nbsp;&nbsp;&nbsp; Upon the reasonable request of Elixir Technology, for the purpose of any dispute resolution proceedings of whatever nature, the Subscriber shall do such necessary acts to perfect and give effect to the Data Messages or Electronic Records, whether digitally signed or not, including but not limited to reducing the contents thereof in writing and physically signing the written records so reduced, to certify that the original Data Message or Electronic Record was validly signed.</p>
				<p>7.4&nbsp;&nbsp;&nbsp; The Subscriber shall not challenge, and hereby waives all his rights (if any) to challenge, the validity or enforceability of any Data Messages, Electronic Records, or agreements or transactions concluded completely or partially through it on the grounds that they were in electronic form, sent electronically and/or the signature appended is only a Digital Signature.</p><span style="font-weight: bold;">
					<li> INTELLECTUAL PROPERTY RIGHTS</li></span>
				<p>8.1&nbsp;&nbsp;&nbsp; All intellectual property rights (including copyright and trade marks) contained in, relating to or in connection with the Websites and Services (including text, graphic, logos, icons, sound recordings and software) are owned by Elixir Technology or our licensors.&nbsp; No materials provided through the Websites or&nbsp; Services, including text, graphics, compilations, computer programs, code and/or software may be reproduced, modified, adapted, distributed, published, displayed, uploaded, broadcast, posted, transmitted or hyperlinked in any manner and in any form without our express, prior written approval and the respective intellectual property owners.</p><span style="font-weight: bold;">
					<li>TERMS OF PAYMENT</li></span>
				<p>9.1&nbsp;&nbsp;&nbsp; In consideration of the provision of the Services by Elixir Technology, the Subscriber agrees as follows:</p>
				<p>(i)&nbsp;&nbsp;&nbsp; The Subscriber shall make payment to Elixir Technology of all applicable charges ("Charges") for the use of the Services, including but not limited to related technical support, in accordance with Elixir Technology's rates and fees, as may be amended from time to time by Elixir Technology.&nbsp; Notification of new rates and fees will be either posted on the Website or sent to the Subscriber via electronic or written means.&nbsp; Payment of Charges shall be in accordance with such payment modes as Elixir Technology may prescribe from time to time.&nbsp; Payments by the Subscriber to Elixir Technology shall be the full amount billed and free of any deduction of any nature whatsoever, including without limitation, deductions for bank charges, official fees, taxes or any other expense or charge incurred by the Subscriber.</p>
				<p>(ii)&nbsp;&nbsp;&nbsp; Unless Elixir Technology agrees otherwise in writing, if the Subscriber opts to make payments by any payment mode other than by direct debit, Elixir Technology shall be entitled to request for a sum of money ("Advance Deposit") from the Subscriber to be placed on deposit with Elixir Technology for the duration of this Agreement.&nbsp; The minimum amount for such Advance Deposit shall be as determined by Elixir Technology from time to time in its sole discretion.&nbsp; Elixir Technology shall be entitled to and the Subscriber hereby authorizes Elixir Technology to deduct such monies from the Advance Deposit as shall be due and outstanding from time to time.&nbsp; Should such Advance Deposit fall below the specified minimum amount, the Subscriber shall top up the difference as soon as possible and in any case within two (2) weeks of notification by Elixir Technology, and inform Elixir Technology when such top up has been completed.</p>
				<p>(iii)&nbsp;&nbsp;&nbsp; If the Subscriber has submitted an authorisation form allowing for direct debit from a bank account designated by the Subscriber ("Designated Account"), Elixir Technology shall be entitled to and the Subscriber hereby authorises Elixir Technology to debit directly, without any notice, the Charges and other monies due to Elixir Technology from the Subscriber's Designated Account.</p>
				<p>(iv)&nbsp;&nbsp;&nbsp; If collection of payment through direct debit is unsuccessful or if payment is not received by Elixir Technology (whichever is the case), late payment interest will be imposed as provided in this Clause 9.1.&nbsp; The Subscriber will be informed of the unsuccessful collection or non-payment and requested to make available the funds and/or make any other arrangement deemed necessary with the bank within a specified time period ("Payment Period"). In direct debit cases, the Subscriber shall inform Elixir Technology when they have completed the arrangement with the bank.</p>
				<p>(v)&nbsp;&nbsp;&nbsp; If Elixir Technology does not receive any payment or notification as aforesaid&nbsp;from the Subscriber within the Payment Period, Elixir Technology will suspend the Services provided to the Subscriber.&nbsp; If Elixir Technology still does not receive any said payment or notification from the Subscriber or is unable to contact the Subscriber at his last known contact details within one (1) week from the Payment Period, Elixir Technology shall be entitled to terminate this Agreement forthwith and the Subscriber will be de-registered as an authorised user of the&nbsp; Services. The above shall be without prejudice to the rights of Elixir Technology in respect of the non-payment of the Charges and interest accrued thereon due from the Subscriber.</p>
				<p>(vi)&nbsp;&nbsp;&nbsp; The Subscriber shall notify Elixir Technology of any discrepancies in the amounts charged within fourteen (14) days of notification of any payable Charges, failing which the amount charged shall be deemed correct and the Subscriber shall not be entitled to dispute the same or bring any action or proceedings against Elixir Technology in respect thereof.</p>
				<p>(vii)&nbsp;&nbsp;&nbsp; Elixir Technology may impose a late payment interest of 1.5% per month or S$5.00 per failed cycle of direct debit whichever is higher, on Charges that are unsuccessfully collected or outstanding from the due collection/payment date until actual collection/payment date.</p>
				<p>(viii)&nbsp;&nbsp;&nbsp; In direct debit cases, the Subscriber will bear all charges imposed by the relevant bank, including but not limited to charges in relation to maintenance of the Subscriber's account, all debits of payment (whether successful or unsuccessful), or overdrawn account.&nbsp; The Subscriber will also bear all charges incurred by Elixir Technology in connection with the unsuccessful debit of payment from the Subscriber's bank account.</p>
				<p>(ix)&nbsp;&nbsp;&nbsp; The Subscriber shall be responsible for the printing of its bills which are made possible electronically as part of the&nbsp;Services.&nbsp; Elixir Technology will not be sending invoices to the Subscriber for the Charges incurred in the use of the&nbsp;Services.&nbsp;&nbsp;&nbsp; Bills for ancillary services such as the Other Services will be rendered by Elixir Technology on a case by case basis and payment terms will be as stated in each bill.</p>
				<p>(x)&nbsp;&nbsp;&nbsp; In the event that Elixir Technology is compelled to commence any legal action to recover unpaid Charges, the Subscriber agrees that Elixir Technology shall be entitled to claim legal costs on a full indemnity basis from the Subscriber.</p><span style="font-weight: bold;">
					<li> DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY</li></span>
				<p>10.1&nbsp;&nbsp;&nbsp; THE SERVICES AND ALL ANCILLARY SERVICES (INCLUDING BUT NOT LIMITED TO TRAINING AND TECHNICAL SUPPORT) ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS.&nbsp; CRIMSONLOGIC DISCLAIMS ALL WARRANTIES OR CONDITIONS OF ANY KIND, TO THE EXTENT PERMITTED BY LAW, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>
				<p>10.2&nbsp;&nbsp;&nbsp; Elixir Technology does not warrant that the Websites and Services will meet Subscriber's requirements or that the Websites and Services will be uninterrupted, timely, secure or error-free.&nbsp; Elixir Technology does not warrant the security of any information transmitted over the Internet as no data transmission over the Internet can be guaranteed as totally secure.&nbsp; Accordingly, any document or information which is transmitted by the Subscriber, whether to Elixir Technology or to any other party, is transmitted at Subscriber's own risk.</p>
				<p>10.3&nbsp;&nbsp;&nbsp; Elixir Technology is not responsible for the availability, content or security of external websites or websites belonging to Service Providers which may be linked or integrated with the Websites.&nbsp; Elixir Technology undertakes no liability, whether in contract, tort or otherwise for the acts, neglects and omissions of the Service Providers or other third parties, including without limitation third party providers of telecommunication, computer or internet services or for faults in or failures of their apparatus, equipment or systems.</p>
				<p>10.4&nbsp;&nbsp;&nbsp; Elixir Technology shall not be liable to the Subscriber or any other party for any damages, loss, cost or expense suffered by the Subscriber or any other party as a result of:</p>
				<p>(i)&nbsp;&nbsp;&nbsp; an action brought by a third party even if such loss was reasonably foreseeable or Elixir Technology has been advised of the possibility of the Subscriber or any other party suffering or incurring the same;</p>
				<p>(ii)&nbsp;&nbsp;&nbsp; the reliance on or use of any data, information, content or matter provided by the Service Provider via the&nbsp;Services or the accuracy, correctness or completeness thereof;</p>
				<p>(iii)&nbsp;&nbsp;&nbsp; any errors, interruptions or other occurrence whatsoever arising out of any form of communications or other facilities not provided by Elixir Technology;</p>
				<p>(iv)&nbsp;&nbsp;&nbsp; any data or other information input, sent or received by or to the Subscriber or through the&nbsp; Services;</p>
				<p>(v)&nbsp;&nbsp;&nbsp; any occurrence not due to Elixir Technology's direct default.</p>
				<p>10.5&nbsp;&nbsp;&nbsp; In no event shall Elixir Technology be liable for any loss of business, profit, goodwill or any type of special, indirect or consequential loss.</p>
				<p>10.6&nbsp;&nbsp;&nbsp; The Subscriber shall indemnify and keep Elixir Technology harmless against any damage or claim by any parties which may arise out of this Agreement and agree to notify such parties in writing that Elixir Technology shall have no liability to them.&nbsp; In the event any claim is made by such parties against Elixir Technology, the Subscriber shall take all steps to enforce its rights including but not limited to the institution of legal proceedings, if necessary, against such parties to restrain them from bringing such claims against Elixir Technology.</p>
				<p>10.7&nbsp;&nbsp;&nbsp; Elixir Technology shall not be responsible for any dealings (i) between the Subscriber and the Service Providers or (ii) between the Subscriber and another Subscriber whether or not such dealings are facilitated through the use of the Services.&nbsp;</p>
				<p>10.8&nbsp;&nbsp;&nbsp; The Subscriber agrees that it shall not bring any claims, actions or proceedings whatsoever against the Service Providers in respect of any damages, loss, cost and expense arising from the use or reliance on the data, information, content or matter provided by the Service Providers via the Website or&nbsp; Services.</p>
				<p>10.9&nbsp;&nbsp;&nbsp; Elixir Technology shall have no liability to the Subscriber for any loss, damage, cost or expense arising from or in connection with this Agreement unless the Subscriber shall have served notice on Elixir Technology within thirty (30) days from the date the event giving rise to the cause of action arose.</p>
				<p>10.10&nbsp;&nbsp;&nbsp; Neither party shall be responsible for failure to perform or fulfil its commitments under this Agreement if such failure is due to any other circumstances outside its control.&nbsp; Such circumstances comprise, but are not confined to, acts of God, war, riots and sabotage.</p>
				<p>10.11&nbsp;&nbsp;&nbsp; Elixir Technology shall not be held responsible for any failure to meet its obligations under this Agreement to the extent that such failure is attributable to the effects of any computer virus.</p>
				<p>10.12&nbsp;&nbsp;&nbsp; In any event, the liability of Elixir Technology for loss, damage, cost or expense to the Subscriber, for any cause whatsoever and regardless of the form of action, whether in contract or in tort including negligence or otherwise, shall not exceed a total of the last three (3) months' payments by the Subscriber to Elixir Technology.</p><span style="font-weight: bold;">
					<li>GOVERNING LAW</li></span>
				<p>11.1&nbsp;&nbsp;&nbsp; This Agreement shall be governed by and construed in accordance with the laws of Singapore. The parties agree to submit to the exclusive jurisdiction of the courts of Singapore.</p>
				<p>11.2&nbsp;&nbsp;&nbsp; Recognizing the global nature of the Internet, the Subscriber agrees to comply with all local rules regarding online conduct, acceptable content and use of the Websites and the Services.&nbsp;Details contained on the Websites have been prepared in accordance with Singapore law and may not satisfy the laws of any other country.&nbsp; Elixir Technology does not warrant that the details on the Website will satisfy the laws of any country other than Singapore.</p><span style="font-weight: bold;">
					<li>TERMINATION OF ACCESS</li></span>
				<p>12.1&nbsp;&nbsp;&nbsp; Either party may terminate this Agreement by thirty (30) days' prior written notice to the other party.</p>
				<p>12.2&nbsp;&nbsp;&nbsp; Upon termination, the Subscriber and its nominees shall immediately cease to use or access the Services.</p>
				<p>12.3&nbsp;&nbsp;&nbsp; Notwithstanding the foregoing, Elixir Technology may cease immediately to provide the Services and to terminate this Agreement forthwith if (i) the Subscriber goes into liquidation or bankruptcy; or (ii) if the Subscriber breaches or fails to conform to any obligation in accordance with this Agreement; or (iii) as provided under Clause 9.1(v) of this Agreement.</p>
				<p>12.4&nbsp;&nbsp;&nbsp; Clauses 5.3 to 5.6, 5.9, 8, 10, 11, 12.4 and 13.1 shall survive the termination of this Agreement.</p><span style="font-weight: bold;">
					<li>GENERAL</li></span>
				<p>13.1&nbsp;&nbsp;&nbsp; The Subscriber shall not, in any litigation proceeding, challenge the admissibility as evidence or the accuracy of a data log or electronic record provided by Elixir Technology in whatever form it may be presented.</p>
				<p>13.2&nbsp;&nbsp;&nbsp; Nothing in this Agreement shall constitute or be deemed to constitute a partnership between Elixir Technology and any Subscriber or Service Provider, nor constitute the appointment of Elixir Technology as agent of any Subscriber or Service Provider.</p>
				<p>13.3&nbsp;&nbsp;&nbsp; A waiver of breach or default under this Agreement by Elixir Technology must be in writing and shall not be a waiver of any other or subsequent default. Failure or delay by Elixir Technology to enforce compliance with any term or condition of this Agreement shall not constitute a waiver of such term or condition.</p>
				<p>13.4&nbsp;&nbsp;&nbsp; If any terms and conditions are held to be invalid, unenforceable or illegal for any reason, the remaining terms and conditions will nevertheless continue in full force.</p>
				<p>13.5&nbsp;&nbsp;&nbsp; The Subscriber shall not assign this Agreement or any part thereof without the prior written consent of Elixir Technology.</p>13.6&nbsp;&nbsp;&nbsp; The Subscriber shall be deemed to have read this Agreement and agree to be bound by the terms hereof.&nbsp; This Agreement shall supersede all proposals, prior agreements, oral or written, and all other communications between the parties relating to the subject matter of this Agreement.
				<p>13.7&nbsp;&nbsp;&nbsp; No part of this Agreement is enforceable under the Contracts (Rights of Third Parties) Act 2002 by a person who is not a party to it.
				</p>
			</ol>
        </div>
      </div>
    </div>
  </div>
</section>

